package com.pico.mvvm.timetonic.timetonictest.domain.model.home

data class Book(
    val invited: Boolean,
    val accepted: Boolean,
    val archived: Boolean,
    val showFpOnOpen: Boolean,
    val sstamp: Long,
    val del: Boolean,
    val hideMessage: String,
    val hideBookMembers: String,
    val description: String?,
    val defaultTemplate: String,
    val isDownloadable: Boolean,
    val canDisableSync: Boolean,
    val b_c: String,
    val b_o: String,
    val cluster: String,
    val tags: List<String>?,
    val langs: List<String>?,
    val contact_u_c: String?,
    val nbNotRead: Int,
    val nbMembers: Int,
    val members: List<Member>,
    val fpForm: FpForm,
    val lastMsg: LastMsg,
    val nbMsgs: Int,
    val userPrefs: UserPrefs,
    val ownerPrefs: OwnerPrefs,
    val sbid: Int,
    val lastMsgRead: Int,
    val lastMedia: Int,
    val favorite: Boolean,
    val order: Int
)
